=== yefengHope/MyLearn/WebRoot/language/language.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- START SNIPPET: noka-tagDtd -->
<!--
   noka-tag configuration DTD.
   Use the following DOCTYPE
  <!DOCTYPE noka PUBLIC
    "-//noka//DTD noka-pro Configuration 3.2//EN"
    "language.dtd">
-->
<!ELEMENT language (page*)>
<!ELEMENT page (option*)>
<!ELEMENT option (#PCDATA)>
<!ATTLIST page
id CDATA #REQUIRED
description CDATA #REQUIRED
>
<!ATTLIST option
key CDATA #REQUIRED
description CDATA #IMPLIED
>

=== yefengHope/MyLearn/WebRoot/language/language_zh-cn.xml
<?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE noka PUBLIC
    "-//noka//DTD noka-pro Configuration 3.2//EN"
    "language.dtd">
<language>
<page id="org.noka.sys" description="系统全局信息">
<option key="ProVersion" description="系统"><![CDATA[Noka Pro V3.5]]></option>
<option key="Projectname" description="项目名称"><![CDATA[Noka porject name]]></option>
<option key="DoubClickClear" description="双击清空"><![CDATA[双击清空]]></option>
<option key="Help" description="使用帮助"><![CDATA[使用帮助]]></option>
<option key="UpdatePass" description="修改密码"><![CDATA[修改密码]]></option>
<option key="ExitSys" description="退出系统"><![CDATA[退出系统]]></option>
<option key="dellselect" description="请选择删除项"><![CDATA[请选择删除项]]></option>
<option key="add" description="请选择删除项"><![CDATA[添加]]></option>
<option key="dell" description="请选择删除项"><![CDATA[删除]]></option>
<option key="update" description="请选择删除项"><![CDATA[修改]]></option>
<option key="nonull" description="该项不能为空"><![CDATA[该项不能为空]]></option>
<option key="adds" description="添加成功！"><![CDATA[添加成功]]></option>
<option key="dells" description="删除成功！"><![CDATA[删除成功]]></option>
<option key="upds" description="修改成功"><![CDATA[修改成功]]></option>
<option key="addf" description="添加失败！"><![CDATA[添加失败]]></option>
<option key="dellf" description="删除失败！"><![CDATA[删除失败]]></option>
<option key="updf" description="修改失败"><![CDATA[修改失败]]></option>
<option key="isdel" description="你确定要删除这些数据吗？"><![CDATA[你确定要删除这些数据吗？]]></option>
<option key="nonullorin" description="该项不能为空"><![CDATA[该项不能为空或者该项已经存在]]></option>
<option key="yes" description="是"><![CDATA[是]]></option>
<option key="no" description="否"><![CDATA[否]]></option>
<option key="save" description="保存"><![CDATA[保存]]></option>
<option key="close" description="关闭"><![CDATA[关闭]]></option>
<option key="worktitle" description="系统管理"><![CDATA[字典表]]></option>
<option key="usertitle" description="系统管理"><![CDATA[用户表]]></option>
<option key="tand" description="并且"><![CDATA[并且]]></option>
<option key="tor" description="或者"><![CDATA[或者]]></option>
<option key="alldept" description="所有部门"><![CDATA[所有部门]]></option>
<option key="thedept" description="本部门"><![CDATA[本部门]]></option>
<option key="thesubdept" description="本部门及下属部门"><![CDATA[本部门及下属部门]]></option>
<option key="usermy" description="用户自己"><![CDATA[用户自己]]></option>
<option key="appdept" description="指定部门"><![CDATA[指定部门]]></option>
<option key="dbcortitle" description="双击修改或查看"><![CDATA[[双击修改]:[双击查看]]]></option>
</page>
<page id="org.menu.jsp" description="菜单管理界面">
<option key="menu_name"><![CDATA[菜单名称]]></option>
<option key="menu_url"><![CDATA[菜单地址]]></option>
<option key="menu_operate"><![CDATA[按钮权限]]></option>
<option key="menu_image"><![CDATA[菜单图标]]></option>
<option key="menu_target"><![CDATA[跳转目标]]></option>
<option key="menu_nburl"><![CDATA[公共权限]]></option>
<option key="menu_taxis"><![CDATA[排序]]></option>
<option key="menu_leve"><![CDATA[级别号]]></option>
<option key="menu_list"><![CDATA[菜单列表]]></option>
</page>
<page id="org.noka.sys.menu" description="系统菜单">
<option key="sysmenu" description="系统菜单"><![CDATA[系统菜单]]></option>
<option key="sysadmin" description="系统管理"><![CDATA[系统管理]]></option>
<option key="basework" description="系统管理"><![CDATA[基础字典]]></option>
<option key="myinfo" description="个人信息"><![CDATA[个人信息]]></option>
<option key="formset" description="系统演示"><![CDATA[表单设置]]></option>
<option key="cozc" description="公司职称"><![CDATA[公司职称]]></option>
<option key="treemenu" description="系统管理"><![CDATA[树形字典]]></option>
<option key="cojg" description="系统管理"><![CDATA[组织机构]]></option>
<option key="treebook" description="系统管理"><![CDATA[树形字典]]></option>
<option key="grxi" description="系统管理"><![CDATA[个人信息]]></option>
<option key="qxgl" description="系统管理"><![CDATA[权限管理]]></option>
<option key="uadmin" description="系统管理"><![CDATA[用户管理]]></option>
<option key="radmin" description="系统管理"><![CDATA[角色管理]]></option>
<option key="bat" description="系统管理"><![CDATA[业务管理]]></option>
<option key="batsub" description="系统管理"><![CDATA[表单管理]]></option>
<option key="ather" description="系统管理"><![CDATA[其它]]></option>
<option key="menuadmin" description="菜单管理"><![CDATA[菜单管理]]></option>
<option key="customer" description="客户管理"><![CDATA[客户管理]]></option>
<option key="customerlist" description="客户管理"><![CDATA[客户列表]]></option>
</page>
<page id="org.login.jsp" description="登录界面信息">
<option key="username" description="用户名"><![CDATA[用户名]]></option>
<option key="userpass" description="密码"><![CDATA[密　码]]></option>
<option key="InputUserPlase" description="请输入用户名"><![CDATA[请输入用户名！]]></option>
<option key="InputPassPalse" description="请输入密码"><![CDATA[请输入密码！]]></option>
<option key="ButtonLoginTitle" description="登录按钮标题"><![CDATA[登录]]></option>
<option key="ButtonCloseTitle" description="取消按钮标题"><![CDATA[取消]]></option>
<option key="OuputNoUser" description="用户名不存在"><![CDATA[提示：用户名不存在]]></option>
<option key="PassErro" description="密码错误"><![CDATA[提示：密码错误]]></option>
<option key="UpassErro" description="用户禁用"><![CDATA[提示：该用户已被禁用]]></option>
</page>
<page id="org.word.jsp" description="基础字点典">
<option key="nameerro" ><![CDATA[名称有误，请重新输入]]></option>
<option key="pxuerro" ><![CDATA[排序有误，请重新输入]]></option>
<option key="name_8" ><![CDATA[名称]]></option>
<option key="name_9" ><![CDATA[部门名称]]></option>
<option key="name_10" ><![CDATA[名称]]></option>
<option key="pxun" ><![CDATA[排序]]></option>
<option key="notes" ><![CDATA[备注]]></option>
<option key="intnonull" ><![CDATA[该项不能为空<br>只能录入1到10位数的正整数]]></option>
<option key="wordlist"><![CDATA[字典信息列表]]></option>
<option key="id"><![CDATA[标识号]]></option>
<option key="upname"><![CDATA[上级名称]]></option>
<option key="upname_7"><![CDATA[上级名称]]></option>
</page>
<page id="org.treeword.jsp" description="树形点典">
<option key="fj" ><![CDATA[分级]]></option>
</page>
<page id="org.myuser.jsp" description="个人信息">
<option key="pname" ><![CDATA[请输入正确的姓名]]></option>
<option key="pmoble" ><![CDATA[请输入正确的手机号码]]></option>
<option key="ptel" ><![CDATA[请输入正确的电话号码]]></option>
<option key="pemail" ><![CDATA[请输入正确的邮箱地址]]></option>
<option key="name" ><![CDATA[姓名]]></option>
<option key="sex" ><![CDATA[性别]]></option>
<option key="bro" ><![CDATA[出生]]></option>
<option key="moble" ><![CDATA[手机]]></option>
<option key="tel" ><![CDATA[电话]]></option>
<option key="email" ><![CDATA[电邮]]></option>
<option key="namenonull" ><![CDATA[姓名不能为空]]></option>
<option key="ptelg" ><![CDATA[请输入正确的电话号码<br>格式为：<br>区号电话号]]></option>
<option key="man" ><![CDATA[男]]></option>
<option key="wman" ><![CDATA[女]]></option>
</page>
<page id="org.user.jsp" description="用户管理">
<option key="usernameerro" ><![CDATA[用户名有误]]></option>
<option key="nameerro" ><![CDATA[用户姓名有误]]></option>
<option key="dbpasserro" ><![CDATA[两次输入的密码不一致]]></option>
<option key="mobileerro" ><![CDATA[手机号码有误]]></option>
<option key="telerro" ><![CDATA[电话号码有误]]></option>
<option key="emailerro" ><![CDATA[电子邮件地址有误]]></option>
<option key="depterro" ><![CDATA[请选择所属部门]]></option>
<option key="suer" ><![CDATA[请选择启用的用户]]></option>
<option key="stopuser" ><![CDATA[请选择禁用的用户]]></option>
<option key="squro" ><![CDATA[请选择需要授权的角色]]></option>
<option key="fprole" ><![CDATA[分配角色]]></option>
<option key="sto" ><![CDATA[禁用]]></option>
<option key="str" ><![CDATA[启用]]></option>
<option key="usern" ><![CDATA[用户名]]></option>
<option key="pass" ><![CDATA[密码]]></option>
<option key="dpass" ><![CDATA[重复密码]]></option>
<option key="deptur" ><![CDATA[所属部门]]></option>
<option key="isstr" ><![CDATA[是否启用]]></option>
<option key="uinfo" ><![CDATA[用户信息]]></option>
<option key="fpsu" ><![CDATA[分配成功]]></option>
<option key="fpfd" ><![CDATA[分配失败]]></option>
<option key="fpdoing" ><![CDATA[您正在为]]></option>
<option key="userfp" ><![CDATA[用户分配角色]]></option>
<option key="allrol" ><![CDATA[全部角色]]></option>
<option key="sdrol" ><![CDATA[已选角色]]></option>
<option key="usfugle" ><![CDATA[直接上级]]></option>
<option key="usselect" ><![CDATA[选择人员]]></option>
</page>
<page id="org.role.jsp" description="角色管理">
<option key="psrole" ><![CDATA[请选择需要授权的角色]]></option>
<option key="prdo" ><![CDATA[请选择需要操作的角色]]></option>
<option key="sqro" ><![CDATA[授权]]></option>
<option key="datafi" ><![CDATA[数据过滤]]></option>
<option key="rolename" ><![CDATA[角色名称]]></option>
<option key="rolelist" ><![CDATA[角色列表]]></option>
<option key="roledatafi" ><![CDATA[角色设置数据过滤]]></option>
<option key="roleqx" ><![CDATA[角色授权]]></option>
<option key="tablename" ><![CDATA[表名]]></option>
<option key="dodept" ><![CDATA[操作部门]]></option>
<option key="oldpass" ><![CDATA[旧密码]]></option>
<option key="newpass" ><![CDATA[新密码]]></option>
<option key="rnespass" ><![CDATA[确认新密码]]></option>
<option key="oldpasserro" ><![CDATA[请输入旧密码]]></option>
<option key="npasserro" ><![CDATA[新密码不能为空]]></option>
<option key="rnpasserro" ><![CDATA[确认新密码不能为空]]></option>
<option key="onpasserro" ><![CDATA[两次输入的密码不一致，请重新输入]]></option>
</page>
<page id="org.popedom.jsp" description="角色权限管理">
<option key="popedomsave" ><![CDATA[保存菜单授权]]></option>
<option key="buttondom" ><![CDATA[保存按钮权限]]></option>
<option key="dfitartedo" ><![CDATA[保存数据过率权限]]></option>
</page>
<page id="org.bottom.jsp" description="info botton">
<option key="usname" ><![CDATA[用户]]></option>
<option key="tname" ><![CDATA[所属部门]]></option>
<option key="starttime" ><![CDATA[登录时间]]></option>
<option key="systime" ><![CDATA[系统时间]]></option>
<option key="Version" ><![CDATA[版本号]]></option>
</page>
<page id="org.userselect.jsp" description="select user">
<option key="role" ><![CDATA[角色]]></option>
<option key="depa" ><![CDATA[部门]]></option>
<option key="all" ><![CDATA[所有]]></option>
<option key="enter" ><![CDATA[确定]]></option>
</page>
</language>
