=== yefengHope/MyLearn/src/noka-tag-6.0.14.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- START SNIPPET: noka-tagDtd -->
<!--
   noka-tag configuration DTD.
   Use the following DOCTYPE
  <!DOCTYPE noka PUBLIC
    "-//noka//DTD noka-tag Configuration 6.0.14//EN"
    "noka-tag-6.0.14.dtd">
-->
<!ELEMENT config (sysconfig?,cache-files?,http-headers?,accord*,dbgrid*,subgrid*,cellbody*,kword*)>
<!ELEMENT sysconfig (option*,file-save?,rewritlist*)>
<!ELEMENT http-headers (headers-public,headers-pravate*)>
<!ELEMENT cache-files (cache-file*)>
<!ELEMENT accord (#PCDATA)>
<!ELEMENT dbgrid (#PCDATA)>
<!ELEMENT subgrid (#PCDATA)>
<!ELEMENT cellbody (#PCDATA)>
<!ELEMENT kword (#PCDATA)>
<!ELEMENT file-save (#PCDATA)>
<!ELEMENT option (#PCDATA)>
<!ELEMENT headers-public (header*)>
<!ELEMENT headers-pravate (header*)>
<!ATTLIST headers-pravate
dir  CDATA #REQUIRED
forpublic (true|false) #REQUIRED
>
<!ELEMENT header (#PCDATA)>
<!ATTLIST header
key  CDATA #REQUIRED
>
<!ATTLIST file-save
type (DISK|DB) #REQUIRED
position CDATA #REQUIRED
>
<!ATTLIST option 
key (default-language|is-dbug|sql-checkvalue|pass-key|db-connection-class|dbutil-auto-close-session|encoding|proxool-alias|db-driver|db-url|db-user|db-password|user-filter|dbgrid-dataserver|spring-sessionFactory|button-filter|rootpath-rule|cookie-domain) #REQUIRED
value CDATA #REQUIRED
>
<!ELEMENT rewritlist (#PCDATA)>
<!ATTLIST rewritlist 
key  CDATA #REQUIRED
revalue CDATA #REQUIRED
type (request|session|const) #REQUIRED
>
<!ATTLIST cache-files 
cache (true|false) #REQUIRED
jszip (true|false) #REQUIRED
cszip (true|false) #REQUIRED
prefix CDATA #REQUIRED
skip  CDATA #IMPLIED
>
<!ELEMENT cache-file (#PCDATA)>
<!ATTLIST cache-file 
extension CDATA #REQUIRED
expires CDATA #REQUIRED
>
<!ATTLIST accord
id CDATA #REQUIRED
>
<!ATTLIST dbgrid
id CDATA #REQUIRED
>
<!ATTLIST subgrid
id CDATA #REQUIRED
>
<!ATTLIST cellbody
id CDATA #REQUIRED
>
<!ATTLIST kword
id CDATA #REQUIRED
value CDATA #REQUIRED
>


<!-- END SNIPPET: noka-tagDtd -->

=== yefengHope/MyLearn/src/noka-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE noka PUBLIC
"-//noka//DTD noka-tag Configuration 6.0.14//EN"
    "noka-tag-6.0.14.dtd">
<config>
<sysconfig>
<option key="default-language" value="zh-CN"></option><!-- 系统默认语言 -->
<option key="db-connection-class" value="org.nokatag.Connection.HibernateConnection"></option>
<option key="is-dbug" value="true"></option><!-- 是否以bug模式运行 -->
<!-- <option key="user-filter" value="org.noka.sso.NSsoFilter"></option>  单点登录系统 -->
<option key="user-filter" value="org.noka.filter.SystemFilter"></option><!-- 系统拦截器 -->
<option key="rootpath-rule" value="1"></option>
<option key="sql-checkvalue" value="'|and|exec|insert|select|delete|update|count|*|%|chr|mid|master|truncate|char|declare|;|or|--|+|,"></option>
<option key="pass-key" value="noka2jkl^swf@#$LKJds567q9KLJ^*1lkjsad"></option><!-- 加密密钥 -->
<file-save position="NK_FU" type="DB"></file-save><!-- 上传文件存放配置 position为存放目标位置 如果是数据库，直接写表名，如果磁盘直接写目录，可以绝对目录如C:/file 或是相对目录如${rootdir}/fileserver type为存放类型 可选DISK表示磁盘 DB表示数据库 -->
<!-- 
	文档替换列表，其中rooturl为系统默认替换，无须设置 
	key为需要替换的关键字，在文档中的写法为${key}
	revalue为取得重设置时用的关键字
	type为取得重设置的类型，支持从request、session、const三种方式
-->
</sysconfig>
<cache-files cache="true" jszip="false" cszip="true" prefix="/script,/skins" skip="a.js,b.js">
<cache-file extension="*.js" expires="30D"></cache-file>
<cache-file extension="*.css" expires="30D"></cache-file>
<cache-file extension="*.jpg" expires="30D"></cache-file>
<cache-file extension="*.png" expires="30D"></cache-file>
<cache-file extension="*.gif" expires="30D"></cache-file>
</cache-files>
<!-- http协议头 -->
<http-headers>
	<headers-public>
		<header key="x-frame-options">SAMEORIGIN</header>
		<header key="X-XSS-Protection">1;mode=block</header>
		<header key="X-Content-Type-Options">nosniff</header>
		<header key="X-UA-Compatible">chrome=1</header>
		<header key="cache-control">max-age=0, s-maxage=100</header>
	</headers-public>
	<headers-pravate dir="/script" forpublic="false">
		<header key="x-content-security-policy">default-src 'self';img-src *;</header>
	</headers-pravate>
</http-headers>

<dbgrid id="1">
<![CDATA[]]>
</dbgrid>
<!-- 子表模板 -->
<subgrid id="1">
<![CDATA[
	你好啊名字：${1}<br>
	你好啊名字：${2}<br>
	你好啊名字：${3}<br>
]]>
</subgrid>
<cellbody id="1">
<![CDATA[
<div style="width: 100px;height: 60px;">
	<div>${2}</div>
	<div>${3}|${4}</div>
</div>
]]>
</cellbody>
<kword id="1" value="absdeghjkmnpqrstuwxyzABCDEFGHIJKLMNPQRST23456789"></kword>
<kword id="2" value="FDABZXSRETOP你好这是什么东西"></kword>
</config>
