=== yefengHope/MyLearn/src/system_config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- START SNIPPET: noka-tagDtd -->
<!--
   noka-tag configuration DTD.
   Use the following DOCTYPE
  <!DOCTYPE noka PUBLIC
    "-//noka//DTD noka-pro Configuration 3.2//EN"
    "system_config.dtd">
-->
<!ELEMENT xmlconst (option*,dbtable-filters?,dbtable-deletes?,prints?,cache-files?)>
<!ELEMENT option (#PCDATA)>
<!ELEMENT dbtable-filters (table*)>
<!ELEMENT prints (print*)>
<!ELEMENT cache-files (cache-file*)>
<!ELEMENT dbtable-deletes (dtable*)>
<!ELEMENT table (#PCDATA)>
<!ELEMENT print (#PCDATA)>
<!ELEMENT cache-file (#PCDATA)>
<!ELEMENT dtable (#PCDATA)>
<!ATTLIST option
key CDATA #REQUIRED
>
<!ATTLIST table
key CDATA #REQUIRED
user-field CDATA #REQUIRED
dept-field CDATA #REQUIRED
lang CDATA #REQUIRED
select CDATA #IMPLIED
>
<!ATTLIST print
id CDATA #REQUIRED
class CDATA #REQUIRED
>
<!ATTLIST cache-file
extension CDATA #REQUIRED
expires CDATA #REQUIRED
>
<!ATTLIST dtable
mtable CDATA #REQUIRED
mfield CDATA #REQUIRED
rtable CDATA #REQUIRED
rfield CDATA #REQUIRED
action (delete|back) #REQUIRED
prompt CDATA #REQUIRED
>

=== yefengHope/MyLearn/src/system_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE noka PUBLIC
    "-//noka//DTD noka-pro Configuration 3.2//EN"
    "system_config.dtd">
<xmlconst>
<option key="dbtable-page-size"><![CDATA[10]]></option><!-- 数据列表每面显示记录总数  -->
<option key="server-manid"><![CDATA[1]]></option><!-- 服务器主id  -->
<option key="server-subid"><![CDATA[2]]></option><!-- 服务器次id  -->
<option key="default-language"><![CDATA[zh-cn]]></option><!-- 默认语言 -->
<option key="path-language"><![CDATA[language]]></option><!--语文件路径 -->
<option key="no-sessionCheck"><![CDATA[setnowurl.nk,login.nk,index.jsp,codeimg_nsk.codeimg,noka.ico,webchecnk.chk,dataserver.ser]]></option><!--排除Session验证的路径,以逗号分隔 -->
<option key="session-publick"><![CDATA[login.nk,main.nk,top.nk,nkwordDbdb.ndbgrid,nkwordDbdbbn.ndbgrid,left.nk,middle.nk,right.nk,rightmenu.nk,bottom.nk,mypasswordupdate.nk,mypassword.nk,ntreeselect_*.tre]]></option><!--需要session才能访问的共公路径 -->
<option key="no-sessionUrl"><![CDATA[${rooturl}/login.nk]]></option><!--session验证失败重定向路径 -->
<option key="no-sqlUrl"><![CDATA[${rooturl}/login.nk]]></option><!--sql验证失败重定向路径 -->
<option key="cache-file"><![CDATA[true]]></option><!--缓存文件 -->
<dbtable-filters><!-- 数据过滤  key指过滤sql的key一般可指表名,user-field 用户id字段,dept-field 用户所在部门字段 lan语言文件的key select对应于数据过滤设置界面上的5个选项，为false表示不显示该选项 -->
	<table key="NK_SYS_WORDBOOK" user-field="WUSER" dept-field="WCWORKDEPT" lang="org.noka.sys.worktitle"></table>
	<table key="NK_SYS_USERINFO" user-field="USID" dept-field="USWORK" lang="org.noka.sys.usertitle" select="true,true,true,false,true"></table>
</dbtable-filters>
<prints>
	<print id="test" class="org.noka.printItem.TestPrint"></print>
</prints>
</xmlconst>
